### ISSUE TITLE
[DISCUSS] Transferring this repository

### ISSUE THREAD

**Issue by shimamoto** [openzipkin-contrib/play-zipkin-tracing#46]
I am looking to contribute this library to openzipkin organization. Current organization is a corporate account, so that I cannot invite users who don't work for the company to organization. One of my expectations in such an effort is to improve maintenance operation. It would be great to move to openzipkin-contrib.

cc @adriancole @takezoe

**Comment by adriancole** [comment]
I'm in favor of this. While there is a potential future where https://github.com/SmartThingsOSS/smartthings-brave-scala becomes contrib or otherwise, I don't think contrib is the right place to choose one solution. Especially, play-zipkin-tracing is a healthy project people use and we should make it easier for people to help with it.

**Comment by takezoe** [comment]
Also already there is brave-akka (https://github.com/openzipkin-contrib/brave-akka) in openzipkin-contrib organization. This library overlaps with play-zipkin-tracing in Akka tracing, but I think that still opezipkin-contrib is a good place to contribute play-zipkin-tracing.

**Comment by shimamoto** [comment]
ah, so how about moving play tracing into openzipkin-contrib as a single project?

**Comment by adriancole** [comment]
@openzipkin/core does anyone have feedback against moving this to openzipkin-contrib? If you are in favor please thumbsup.

**Comment by adriancole** [comment]
whoops that alias doesn't work outside our org :) manually doing it. cc @abesto @basvanbeek @devinsba @eirslett @jcarres-mdsol @jcchavezs @llinder @michaelsembwever @shakuzen @zeagord

**Comment by adriancole** [comment]
and most recently @jeqo

**Comment by adriancole** [comment]
ok we have sufficient interest. Can someone add me as a repo owner then I can move it retaining the same committers as we have now

**Comment by shimamoto** [comment]
@adriancole Unfortunately, I cannot add you to current organization because of a corporate account. I think there are basically two options:

One, I transfer this repository to openzipkin-contrib organization.
Two, you create a new repository on openzipkin-contrib organization, and I can import a Git repository only.

**Comment by adriancole** [comment]
I just gave you rights on openzipkin-contrib so you can do the transfer.
Thanks!

**Comment by shimamoto** [comment]
Done!
